services:
  - type: web
    name: esp32-aliyun-tts-proxy
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ALIYUN_ACCESS_KEY_ID
        sync: false
      - key: ALIYUN_ACCESS_KEY_SECRET
        sync: false
      - key: ALIYUN_APP_KEY
        sync: false
